$('document').ready(function(){
     $('#school').on('mouseover',function(){
     	$('#courelist').show();
     });
      $('#courelist').on('mouseleave',function(){
     	$('#courelist').hide();
     });
      $('#course').on('mouseover',function(){
     	$('#VIP-course').show();
     });
      $('#VIP-course').on('mouseleave',function(){
     	$('#VIP-course').hide();
     });
      $('#block').on('mouseover',function(){
     	$('#jikeblock').show();
     });
      $('#jikeblock').on('mouseleave',function(){
     	$('#jikeblock').hide();
     });
      $('#search').on('click',function(){
         $('#searchbox').show();
      });
      $('#close-btn').on('click',function(){
      	$('#searchbox').hide();
      });
      //課程庫的顯示與隱藏
      $('#cg1').on('mouseover',function(){
      	$('.list-show').hide();
        $('#yidong').show();
      });
      $('#yidong').on('mouseleave',function(){
      	$('.list-show').hide();
      });

      $('#cg2').on('mouseover',function(){
      	$('.list-show').hide();
        $('#qianduan').show();
      });
      $('#qianduan').on('mouseleave',function(){
      	$('.list-show').hide();
      });
      $('#cg3').on('mouseover',function(){
      	$('.list-show').hide();
        $('#houduan').show();
      });
      $('#houduan').on('mouseleave',function(){
      	$('.list-show').hide();
      });
      $('#cg4').on('mouseover',function(){
      	$('.list-show').hide();
        $('#jichu').show();
      });
      $('#jichu').on('mouseleave',function(){
      	$('.list-show').hide();
      });
      $('#cg5').on('mouseover',function(){
      	$('.list-show').hide();
        $('#yunshuju').show();
      });
      $('#yunshuju').on('mouseleave',function(){
      	$('.list-show').hide();
      });
      $('#cg6').on('mouseover',function(){
      	$('.list-show').hide();
        $('#zhineng').show();
      });
      $('#zhineng').on('mouseleave',function(){
      	$('.list-show').hide();
      });
      $('#cg7').on('mouseover',function(){
      	$('.list-show').hide();
        $('#shujuku').show();
      });
      $('#shujuku').on('mouseleave',function(){
      	$('.list-show').hide();
      });
      $('#cg8').on('mouseover',function(){
      	$('.list-show').hide();
        $('#rz-text').show();
      });
      $('#rz-text').on('mouseleave',function(){
      	$('.list-show').hide();
      });
      $('#cg9').on('mouseover',function(){
      	$('.list-show').hide();
        $('#op-IT').show();
      });
      $('#op-IT').on('mouseleave',function(){
      	$('.list-show').hide();
      });
      $('#cg11').on('mouseover',function(){
      	$('.list-show').hide();
        $('#disg-text').show();
      });

      $('#disg-text').on('mouseleave',function(){
      	$('.list-show').hide();
      });
            //课程库
      $('.type-title-one').on('mouseover',function(){
      	 $('dd').hide();
      	 $('#typ1').show();
      });
       $('#typ1').on('mouseleave',function(){
      	 $('#typ1').hide();
      });
       $('.type-title-tow').on('mouseover',function(){
      	 $('dd').hide();
      	 $('#typ2').show();
      });
       $('#typ2').on('mouseleave',function(){
      	 $('#typ2').hide();
      });
        $('.type-title-three').on('mouseover',function(){
      	 $('dd').hide();
      	 $('#typ3').show();
      });
        $('#typ3').on('mouseleave',function(){
      	 $('#typ3').hide();
      });
         $('.type-title-forth').on('mouseover',function(){
      	 $('dd').hide();
      	 $('#typ4').show();
      });
         $('#typ4').on('mouseleave',function(){
      	 $('#typ4').hide();
      });
         $('#app').on('mouseover',function(){
         	$('#app-p').show();
         });
         $('#app-p').on('mouseleave',function(){
         	$('#app-p').hide();
         });
         //分页条
         $('.btn1').on('click',function(){
         	$('.page').hide();
         	$('#page1').show();
         });
         $('#btn2').on('click',function(){
         	$('.page').hide();
         	$('#page2').show();
         });
         $('#btn3').on('click',function(){
         	$('.page').hide();
         	$('#page3').show();
         });
         $('#btn4').on('click',function(){
         	$('.page').hide();
         	$('#page4').show();
         });

         $('#kuai').on('click',function(){
         	$('.lesson').hide();
         	$('#lesson-list').show();
         });
         $('#list').on('click',function(){
         	$('.lesson').hide();
         	$('#lesson-list2').show();
         });










});